### ISSUE TITLE
Heterogeneous lookup for unordered containers does not work in VS 16.6.0 Preview 2.1

### ISSUE THREAD

**Issue by matbech** [microsoft/STL#683]
This is the same issue as previously reported here:
https://developercommunity.visualstudio.com/content/problem/909973/heterogeneous-lookup-for-unordered-containers-does.html

But even with the proposed change:
std::unordered_map<std::string, int, string_hash, std::equal_to<>> map;
compilation fails.

```
// Code is based on this paper: https://wg21.link/P0919R3
#include <string_view>
#include <unordered_map>
#include <string>

using namespace std;

struct string_hash {
    using transparent_key_equal = std::equal_to<>;  // Pred to use
    using hash_type = std::hash<std::string_view>;  // just a helper local type
    size_t operator()(std::string_view txt) const { return hash_type{}(txt); }
    size_t operator()(const std::string& txt) const { return hash_type{}(txt); }
    size_t operator()(const char* txt) const { return hash_type{}(txt); }
};

std::unordered_map<std::string, int, string_hash, std::equal_to<>> map;

int main()
{
    map.find("abc");
    std::string_view s = "this is view";
    map.find(s); // <- this does not compiles

    return 0;
}
```

Compilation error:

```
error C2664: 'std::_List_const_iterator<std::_List_val<std::_List_simple_types<_Ty>>> std::_Hash<std::_Umap_traits<_Kty,int,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::find<void>(const _Kty &) const': cannot convert argument 1 from 'std::string_view' to 'const _Kty &'
1>        with
1>        [
1>            _Ty=std::pair<const std::string,int>,
1>            _Kty=std::string,
1>            _Hasher=string_hash,
1>            _Keyeq=std::equal_to<void>,
1>            _Alloc=std::allocator<std::pair<const std::string,int>>
1>        ]
1>        and
1>        [
1>            _Kty=std::string
1>        ]
1>xxx.cpp(47,13): message : Reason: cannot convert from 'std::string_view' to 'const _Kty'
1>        with
1>        [
1>            _Kty=std::string
1>        ]
1>xxx.cpp(47,12): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.26.28720\include\xhash(1336,25): message : see declaration of 'std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::find'
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=int,
1>            _Hasher=string_hash,
1>            _Keyeq=std::equal_to<void>,
1>            _Alloc=std::allocator<std::pair<const std::string,int>>
1>        ]
```

**Comment by miscco** [comment]
Unfortunately your code is indeed ill formed. There was a similar issue recently (#623)

The problem is that you forgot to provide a transparent comparator. A working example is:
```cpp
#include <string>
#include <string_view>
#include <unordered_map>

struct string_compare {
    using is_transparent = void;  // Pred to use
    bool operator()(std::string key, std::string_view txt) const { return key == txt; }
    bool operator()(std::string_view key, std::string_view txt) const { return key == txt; }
};

struct string_hash {
    using is_transparent = void;  // Pred to use
    using transparent_key_equal = string_compare;
    size_t operator()(std::string_view txt) const { return std::hash<std::string_view>{}(txt); }
    size_t operator()(const std::string& txt) const { return std::hash<std::string>{}(txt); }
};

int main()
{   
    std::unordered_map<std::string, int, string_hash, string_compare> map;
    map["test"] = 1;                              // converts to std::string
    auto it = map.find(std::string_view("test")); // should compile
    return 0;
}
```

So this 
```cpp
std::unordered_map<std::string, int, string_hash, std::equal_to<>> map;
```

should read (with an apropriately defined `string_compare`)
```cpp
std::unordered_map<std::string, int, string_hash, string_compare> map;
```

**Comment by miscco** [comment]
@BillyONeal Your comment was correct in that one needs to define a suitable comparator but you forgot to provide the correct one. Could you change the comment from the developer community?

**Comment by matbech** [comment]
Thank you. Shouldn't this be a const reference here:
   bool operator()(std::string key, std::string_view txt) const { return key == txt; }
->
   bool operator()(const std::string& key, std::string_view txt) const { return key == txt; }

**Comment by AdamBucior** [comment]
> The problem is that you forgot to provide a transparent comparator

Pretty sure that `equal_to<>` is transparent.

**Comment by matbech** [comment]
I think this is the correct solution now:

```
#include <string>
#include <string_view>
#include <unordered_map>

struct string_hash {
    using is_transparent = void;
    [[nodiscard]] size_t operator()(std::string_view txt) const { return std::hash<std::string_view>{}(txt); }
    [[nodiscard]] size_t operator()(const std::string& txt) const { return std::hash<std::string>{}(txt); }
};

int main()
{   
    std::unordered_map<std::string, int, string_hash, std::equal_to<>> map;
    map["test"] = 1;                              // converts to std::string
    auto it = map.find(std::string_view("test")); // should compile
    return 0;
}

**Comment by miscco** [comment]
> Pretty sure that `equal_to<>` is transparent.

I dont think so. How would `equal_to` know how I want to compare some arbitrary types. `string_view` seems easy because it is convertible to `string` but if you take some random classes `foo` and `bar` how would that work?

> I think this is the correct solution now:
> 
> ```
> #include <string>
> #include <string_view>
> #include <unordered_map>
> 
> struct string_hash {
>     using is_transparent = void;
>     [[nodiscard]] size_t operator()(std::string_view txt) const { return std::hash<std::string_view>{}(txt); }
>     [[nodiscard]] size_t operator()(const std::string& txt) const { return std::hash<std::string>{}(txt); }
> };
> 
> int main()
> {   
>     std::unordered_map<std::string, int, string_hash, std::equal_to<>> map;
>     map["test"] = 1;                              // converts to std::string
>     auto it = map.find(std::string_view("test")); // should compile
>     return 0;
> }
> ```

This cannot be the solution as `equal_to` does not fulfill `is_transparent` which is required by the [standard ](https://eel.is/c++draft/unord.req#17)

```cpp
#include <string>
#include <string_view>
#include <unordered_map>

struct string_compare {
    using is_transparent = void;  // Pred to use
    bool operator()(const std::string& key, std::string_view txt) const { return key == txt; }
    bool operator()(std::string_view key, std::string_view txt) const { return key == txt; }
};

struct string_hash {
    using is_transparent = void;  // <-- It does not work without this trait
    size_t operator()(std::string_view txt) const { return std::hash<std::string_view>{}(txt); }
    size_t operator()(const std::string& txt) const { return std::hash<std::string>{}(txt); }
};

int main()
{   
    std::unordered_map<std::string, int, string_hash, string_compare> map;
    map["test"] = 1;                              // converts to std::string
    auto it = map.find(std::string_view("test")); // should compile
    return 0;
}
```

**Comment by AdamBucior** [comment]
`equal_to<>` is transparent
https://github.com/microsoft/STL/blob/260cfafb634fe3ed64aa33242753d474170d2e2f/stl/inc/xstddef#L195-L205

**Comment by BillyONeal** [comment]
> How would `equal_to` know how I want to compare some arbitrary types.

The same way `operator==` knows how to compare arbitrary types :)
