### ISSUE TITLE
<vector>: vector with incomplete type with C++20.

### ISSUE THREAD

**Issue by fsb4000** [microsoft/STL#2720]
**Describe the bug**
I don't know if it should work but it worked in VS 2019 and VS 2022 17.0.
It is broken since VS 2022 17.1

https://gcc.godbolt.org/z/Pr5dq74r8

**Command-line test case**
```
C:\Temp>type repro.cpp
#include <vector>

class X;
void foo(const std::vector<X> & = {});

C:\Temp>cl /EHsc /std:c++20 /c /W4 /WX .\repro.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31424 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
C:\Dev\STL\out\build\x64\out\inc\vector(1893): error C2036: 'X *': unknown size
C:\Dev\STL\out\build\x64\out\inc\vector(1881): note: while compiling class template member function 'void std::vector<X,std::allocator<X>>::_Tidy(void) noexcept'
C:\Dev\STL\out\build\x64\out\inc\vector(791): note: see reference to function template instantiation 'void std::vector<X,std::allocator<X>>::_Tidy(void) noexcept' being compiled
main.cpp(4): note: see reference to class template instantiation 'std::vector<X,std::allocator<X>>' being compiled
```

**Expected behavior**
It worked before. Maybe it should work. It works in C++17.
It works in C++20 without `= {}`. https://gcc.godbolt.org/z/EW3a1Ena4

**STL version**
```
Microsoft Visual Studio Community 2022 Preview

Version 17.3.0 Preview 1.0
```

**Additional context**
Also tracked by DevCom-10041628

`clang-cl` reports this
```
clang-cl /EHsc /std:c++20 /c /W4 /WX main.cpp
In file included from main.cpp:1:
In file included from C:\Dev\STL\out\build\x64\out\inc\vector:11:
In file included from C:\Dev\STL\out\build\x64\out\inc\xmemory:14:
In file included from C:\Dev\STL\out\build\x64\out\inc\new:11:
In file included from C:\Dev\STL\out\build\x64\out\inc\exception:12:
C:\Dev\STL\out\build\x64\out\inc\type_traits(780,50): error: incomplete type 'X' used in type trait expression
struct is_trivially_destructible : bool_constant<__is_trivially_destructible(_Ty)> {
                                                 ^
C:\Dev\STL\out\build\x64\out\inc\type_traits(59,53): note: in instantiation of template class 'std::is_trivially_destructible<X>' requested here
struct conjunction<_First, _Rest...> : _Conjunction<_First::value, _First, _Rest...>::type {
                                                    ^
C:\Dev\STL\out\build\x64\out\inc\type_traits(64,44): note: in instantiation of template class 'std::conjunction<std::is_trivially_destructible<X>, std::disjunction<std::_Is_default_allocator<std::allocator<X>>,
      std::_Has_no_alloc_destroy<std::allocator<X>, X *>>>' requested here
_INLINE_VAR constexpr bool conjunction_v = conjunction<_Traits...>::value;
                                           ^
C:\Dev\STL\out\build\x64\out\inc\xmemory(946,20): note: in instantiation of variable template specialization 'std::conjunction_v<std::is_trivially_destructible<X>, std::disjunction<std::_Is_default_allocator<std::allocator<X>>,
      std::_Has_no_alloc_destroy<std::allocator<X>, X *>>>' requested here
    if constexpr (!conjunction_v<is_trivially_destructible<_Ty>, _Uses_default_destroy<_Alloc, _Ty*>>) {
                   ^
C:\Dev\STL\out\build\x64\out\inc\vector(1891,13): note: in instantiation of function template specialization 'std::_Destroy_range<std::allocator<X>>' requested here
            _Destroy_range(_Myfirst, _Mylast, _Al);
            ^
C:\Dev\STL\out\build\x64\out\inc\vector(791,9): note: in instantiation of member function 'std::vector<X>::_Tidy' requested here
        _Tidy();
        ^
main.cpp(4,32): note: in instantiation of member function 'std::vector<X>::~vector' requested here
void foo(const std::vector<X>& = {});
                               ^
main.cpp(3,7): note: forward declaration of 'X'
class X;
      ^
In file included from main.cpp:1:
In file included from C:\Dev\STL\out\build\x64\out\inc\vector:11:
C:\Dev\STL\out\build\x64\out\inc\xmemory(946,20): error: constexpr if condition is not a constant expression
    if constexpr (!conjunction_v<is_trivially_destructible<_Ty>, _Uses_default_destroy<_Alloc, _Ty*>>) {
                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Dev\STL\out\build\x64\out\inc\vector(1891,13): note: in instantiation of function template specialization 'std::_Destroy_range<std::allocator<X>>' requested here
            _Destroy_range(_Myfirst, _Mylast, _Al);
            ^
C:\Dev\STL\out\build\x64\out\inc\vector(791,9): note: in instantiation of member function 'std::vector<X>::_Tidy' requested here
        _Tidy();
        ^
main.cpp(4,32): note: in instantiation of member function 'std::vector<X>::~vector' requested here
void foo(const std::vector<X>& = {});
                               ^
In file included from main.cpp:1:
In file included from C:\Dev\STL\out\build\x64\out\inc\vector:11:
C:\Dev\STL\out\build\x64\out\inc\xmemory(947,33): error: arithmetic on a pointer to an incomplete type 'std::_Default_allocator_traits<std::allocator<X>>::value_type' (aka 'X')
        for (; _First != _Last; ++_First) {
                                ^ ~~~~~~
main.cpp(3,7): note: forward declaration of 'X'
class X;
      ^
In file included from main.cpp:1:
In file included from C:\Dev\STL\out\build\x64\out\inc\vector:11:
C:\Dev\STL\out\build\x64\out\inc\xmemory(69,56): error: invalid application of 'alignof' to an incomplete type 'X'
_INLINE_VAR constexpr size_t _New_alignof = (_STD max)(alignof(_Ty),
                                                       ^~~~~~~~~~~~
C:\Dev\STL\out\build\x64\out\inc\xmemory(834,21): note: in instantiation of variable template specialization 'std::_New_alignof<X>' requested here
        _Deallocate<_New_alignof<_Ty>>(_Ptr, sizeof(_Ty) * _Count);
                    ^
C:\Dev\STL\out\build\x64\out\inc\vector(1893,17): note: in instantiation of member function 'std::allocator<X>::deallocate' requested here
            _Al.deallocate(_Myfirst, static_cast<size_type>(_Myend - _Myfirst));
                ^
C:\Dev\STL\out\build\x64\out\inc\vector(791,9): note: in instantiation of member function 'std::vector<X>::_Tidy' requested here
        _Tidy();
        ^
main.cpp(4,32): note: in instantiation of member function 'std::vector<X>::~vector' requested here
void foo(const std::vector<X>& = {});
                               ^
main.cpp(3,7): note: forward declaration of 'X'
class X;
      ^
In file included from main.cpp:1:
In file included from C:\Dev\STL\out\build\x64\out\inc\vector:11:
C:\Dev\STL\out\build\x64\out\inc\xmemory(834,46): error: invalid application of 'sizeof' to an incomplete type 'X'
        _Deallocate<_New_alignof<_Ty>>(_Ptr, sizeof(_Ty) * _Count);
                                             ^~~~~~~~~~~
C:\Dev\STL\out\build\x64\out\inc\vector(1893,17): note: in instantiation of member function 'std::allocator<X>::deallocate' requested here
            _Al.deallocate(_Myfirst, static_cast<size_type>(_Myend - _Myfirst));
                ^
C:\Dev\STL\out\build\x64\out\inc\vector(791,9): note: in instantiation of member function 'std::vector<X>::_Tidy' requested here
        _Tidy();
        ^
main.cpp(4,32): note: in instantiation of member function 'std::vector<X>::~vector' requested here
void foo(const std::vector<X>& = {});
                               ^
main.cpp(3,7): note: forward declaration of 'X'
class X;
      ^
In file included from main.cpp:1:
C:\Dev\STL\out\build\x64\out\inc\vector(1893,68): error: arithmetic on a pointer to an incomplete type 'std::_Default_allocator_traits<std::allocator<X>>::value_type' (aka 'X')
            _Al.deallocate(_Myfirst, static_cast<size_type>(_Myend - _Myfirst));
                                                            ~~~~~~ ^
C:\Dev\STL\out\build\x64\out\inc\vector(791,9): note: in instantiation of member function 'std::vector<X>::_Tidy' requested here
        _Tidy();
        ^
main.cpp(4,32): note: in instantiation of member function 'std::vector<X>::~vector' requested here
void foo(const std::vector<X>& = {});
                               ^
main.cpp(3,7): note: forward declaration of 'X'
class X;
      ^
6 errors generated.
```

**Comment by cpplearner** [comment]
Apparently this is related to constexpr destructor.

Reduced:

```c++
#if __cpp_constexpr_dynamic_alloc
#define CONSTEXPR20 constexpr
#else
#define CONSTEXPR20
#endif

template<class T>
struct A {
constexpr A() {}
CONSTEXPR20 ~A() { T t; }
};

struct B;
void f(const A<B>& = {});
```

**Comment by fsb4000** [comment]
great @cpplearner 

VS 2022 17.0 and gcc 12.1 allow that.
VS 2022 17.1+ and clang don't allow that.

https://gcc.godbolt.org/z/3h7e5Mcqx

**Comment by CaseyCarter** [comment]
Workaround: artificially templatize so the semantics constraints on the default argument aren't evaluated until it is used by some callsite: https://gcc.godbolt.org/z/aMr6Psa8o

(I'm not yet sure what the expected behavior is here.)

**Comment by frederick-vs-ja** [comment]
I don't know what's happening. Presumably there either a bug in the Standard or at least one compiler.

I used to think this is related to the rule in [[expr.const]/(15.3)](https://eel.is/c++draft/expr.const#15.3), but I was likely wrong.

With non-constexpr destructor:
| default argument → | `{}` | `A<B>{}` | `A<B>()` |
|---|---|---|---|
| msvc 17.0  | √ | √ | √ |
| msvc 17.1+ | √ | √ | √ |
| clang 14 | √ | √ | √ |
| gcc 12 | √ | × | × |

With constexpr destructor:
| default argument → | `{}` | `A<B>{}` | `A<B>()` |
|---|---|---|---|
| msvc 17.0 | √ | √ | √ |
| msvc 17.1+ | × | × | × |
| clang 14 | × | × | × |
| gcc 12 | √ | × | × |

**Comment by StephanTLavavej** [comment]
We should show @cpplearner's reduced example (thanks!) to a compiler dev.

**Comment by fsb4000** [comment]
from Discord:

Cameron DaCamara: 
>I'm pretty convinced this is a source bug and that GCC hasn't quite implemented [P0859R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0859r0.html) fully yet.  The reason this is now observable with newer MSVC versions is because the compiler is required to instantiate special member functions if they could be potentially used for constant evaluation.  Since the default argument here is going to end up being assigned to a variable the ctor and dtor are actually odr-used in the default argument.

**Comment by CaseyCarter** [comment]
Ok, this appears to be by design. Now that C++20 has made `vector`'s destructor `constexpr`, it must be instantiated by this potential use. Workarounds are (1) making the function a template, in which case the default argument isn't potentially-evaluated until a call site actually uses it, (2) removing the default argument, (3) don't declare the function with the default argument until the element type is defined, (4) declare an `extern const std::vector<X>` variable to use as the default argument which is defined in some TU where `X` is complete.

**Comment by Amaroker** [comment]
@CaseyCarter

After unique_ptr was made constexpr in 17.3, it has the same problem with default values. No surprise, but if the compiler front-end team decides to make it work with vector, I think they should make it work with unique_ptr as well.

```
#include <memory>
class my_type; // a simple forward declaration was enough in version 17.2

struct X
{
  X();
  ~X();

  std::unique_ptr<my_type> unique = nullptr;  // error C2027 in version 17.3
  
  void foo(const std::unique_ptr<my_type>& = nullptr); // error C2027 in version 17.3
};
```
