### PR TITLE
Fix `pair::swap(const pair&)` and `tuple::swap(const tuple&)` errors with `__declspec(dllexport)`

### LINKED ISSUE #3013: `<utility>`: `pair::swap(const pair&)` interacts badly with `__declspec(dllexport)`
This is a regression caused by merging #2687 in VS 2022 17.3 Preview 2:

```
C:\Temp>type meow.cpp
```
```cpp
#include <utility>
using namespace std;

struct __declspec(dllexport) MyPair : pair<int, int> {};
```
```
C:\Temp>cl /EHsc /nologo /W4 /MD /c /std:c++20 meow.cpp
meow.cpp

C:\Temp>cl /EHsc /nologo /W4 /MD /c /std:c++latest meow.cpp
meow.cpp
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\utility(107): error C2672: 'swap': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\type_traits(1965): note: could be 'void std::swap(_Ty (&)[_Size],_Ty (&)[_Size]) noexcept(<expr>)'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\utility(107): note: 'void std::swap(_Ty (&)[_Size],_Ty (&)[_Size]) noexcept(<expr>)': could not deduce template argument for '_Ty (&)[_Size]' from '_Ty'
        with
        [
            _Ty=int
        ]
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\type_traits(1965): note: see declaration of 'std::swap'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\type_traits(1962): note: or       'void std::swap(_Ty &,_Ty &) noexcept(<expr>)'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\utility(106): note: 'void std::swap(_Ty &,_Ty &) noexcept(<expr>)': could not deduce template argument for '_Enabled'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\type_traits(1962): note: see declaration of 'std::swap'
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\utility(408): note: see reference to function template instantiation 'void std::_Swap_adl<const _Ty1>(_Ty &,_Ty &) noexcept(false)' being compiled
        with
        [
            _Ty1=int,
            _Ty=int
        ]
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\include\utility(406): note: while compiling class template member function 'void std::pair<int,int>::swap(const std::pair<int,int> &) noexcept(false) const'
meow.cpp(4): note: see reference to class template instantiation 'std::pair<int,int>' being compiled
```

Relevant code:

https://github.com/microsoft/STL/blob/2263d931f48a4e196036b2523af7a0048bb96b46/stl/inc/utility#L331-L339

WG21-N4910 [[pairs.pair]/45.2](https://eel.is/c++draft/pairs.pair#45.2) says:

> *Mandates:* For the second overload, `is_swappable_v<const T1>` is `true` and `is_swappable_v<const T2>` is `true`.

So we aren't supposed to constrain this, but that interacts badly with `dllexport` which tries to instantiate everything.

I suspect that we need the `template <int = 0>` workaround, also applied to `tuple`.

Originally reported as DevCom-10109884 and internal VSO-1586226 / AB#1586226 .

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Fixes #3013, a high-priority customer-reported bug (see DevCom-10109884).

Normally, member functions of class templates are instantiated "on demand". (I like to remember this rule by thinking of `list<T>`, which does not require `T` to be less-than comparable until `list<T>::sort()` is called.) However, if a user derives from a Standard Library class (which we don't encourage, but which is widely done) and then dllexports their derived class, that attempts to instantiate all member functions (that are not templated themselves).

By adding member functions (as required by the Standard) that won't compile when force-instantiated like this, #2687 regressed this scenario. The fix is simple (and something we've used elsewhere): add `template <int = 0>` to make instantiation truly on-demand. Conveniently, we already have a test we can expand.

(Note: I explored using `requires` to fix this, but that's more verbose and ran into other compiler errors.)

### CODE REVIEW

**Review by strega-nil-ms — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by AraHaan** [comment]
I think this looks good.

**Review by evelynmarie — APPROVED** [review]
Looks good to me.

**Comment by CaseyCarter** [comment]
Thanks for fixing this _pair_ of issues - I'm sure our customers where about _to pull_ their hair out!
