### PR TITLE
Implement P0448R4 spanstream

### LINKED ISSUE #1970: P0448R4 `<spanstream>`
[P0448R4](https://wg21.link/P0448R4) `<spanstream>`

Feature-test macro:
`#define __cpp_lib_spanstream 202106L`

@CaseyCarter's internal VS-PR-339694 has taught the IDE to recognize this as a C++ header.

### PR DESCRIPTION
**Pull request by miscco**
This implements spanstream that was recently voted into C++23

Fixes #1970

### CODE REVIEW

File: stl/inc/iosfwd [hunk 1]
```diff
@@ -192,6 +192,16 @@ template <class _Elem, class _Traits = char_traits<_Elem>, class _Alloc = alloca
...
+#if _HAS_CXX23
+template <class _Elem, class _Traits = char_traits<_Elem>>
+class basic_spanbuf;
+template <class _Elem, class _Traits = char_traits<_Elem>>
+class basic_ispanstream;
+template <class _Elem, class _Traits = char_traits<_Elem>>
+class basic_ospanstream;
+template <class _Elem, class _Traits = char_traits<_Elem>>
+class basic_spanstream;
+#endif // _HAS_CXX23
```
Comment (AdamBucior) [inline stl/inc/iosfwd:204]: `<iosfwd>` is missing `spanstream`, `wspanstream`, etc.

Comment (miscco) [reply stl/inc/iosfwd:204]: Good catch, I thought they should be located in `<spanstream>`

Comment (miscco) [reply stl/inc/iosfwd:204]: Now that I checked we only have an TR1 test for `<iosfwd>` is that something we should add?

Comment (StephanTLavavej) [reply stl/inc/iosfwd:204]: Yeah, it would make sense to add test coverage to `std` for `<iosfwd>` - the only reason we didn't have any is that the header hasn't received extensive changes recently, and we add test coverage to `std` on an as-needed basis.

(If you're asking whether we should modify `tr1`, we generally refrain from adding test coverage to that legacy suite, although we'll fix it in response to breaking changes. In rare situations, adding test coverage to `tr1` makes sense as the easiest option, e.g. it had infrastructure for testing random number engines, where just adding a few lines was easier than replicating that machinery in `std`.)

File: stl/inc/spanstream [hunk 2]
```diff
@@ -0,0 +1,382 @@
...
+    basic_spanbuf(const basic_spanbuf&) = delete;
+    basic_spanbuf(basic_spanbuf&& _Right)
+        : _Mysb(_STD move(_Right)), _Mode(_STD move(_Right._Mode)), _Buf(_STD move(_Right._Buf)) {
+        _Right.setp(nullptr, nullptr, nullptr);
+        _Right.setg(nullptr, nullptr, nullptr);
+    }
+
+    // [spanbuf.assign], assignment and swap
+    basic_spanbuf& operator=(const basic_spanbuf&) = delete;
+    basic_spanbuf& operator                        =(basic_spanbuf&& _Right) {
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/inc/spanstream:69]: Adding a newline between these lines will prevent clang-format from attempting to align the `=` signs. (Really we should report this upstream.)

File: stl/inc/iosfwd (hunk 1 above)
Comment (miscco) [reply stl/inc/iosfwd:204]: Added a test for the forward declarations

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 3]
```diff
@@ -0,0 +1,1014 @@
...
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <algorithm>
+#include <assert.h>
+#include <span>
+#include <spanstream>
+#include <string_view>
+#include <type_traits>
+using namespace std;
```
Comment (AdamBucior) [inline tests/std/tests/P0448R4_spanstream/test.cpp:12]:
```suggestion
#include <type_traits>

using namespace std;
```

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 4]
```diff
@@ -0,0 +1,1014 @@
...
+        assert(static_cast<test_buf*>(second.rdbuf())->egptr() == end(buffer2));
+        assert(static_cast<test_buf*>(second.rdbuf())->pbase() == buffer2);
+        assert(static_cast<test_buf*>(second.rdbuf())->pptr() == buffer2);
+        assert(static_cast<test_buf*>(second.rdbuf())->epptr() == end(buffer2));
+    }
+
+    {
+        // rdbuf
+        // ^^^ look above ^^^
+    }
```
Comment (AdamBucior) [inline tests/std/tests/P0448R4_spanstream/test.cpp:694]: Are these tests work in progress? This comment is very confusing.

File: stl/inc/spanstream [hunk 5]
```diff
@@ -0,0 +1,392 @@
...
+#pragma pack(push, _CRT_PACKING)
+#pragma warning(push, _STL_WARNING_LEVEL)
+#pragma warning(disable : _STL_DISABLED_WARNINGS)
+_STL_DISABLE_CLANG_WARNINGS
+#pragma push_macro("new")
+#undef new
+
+_STD_BEGIN
+
+// CLASS TEMPLATE basic_spanbuf
```
[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/spanstream:32]: I was just told to add them 😿

File: stl/inc/spanstream [hunk 6]
```diff
@@ -0,0 +1,392 @@
...
+    }
+
+    virtual _Mysb* __CLR_OR_THIS_CALL setbuf(_Elem* _Buffer, streamsize _Count) override {
+        this->span(_STD span<_Elem>{_Buffer, static_cast<size_t>(_Count)});
+        return this;
+    }
+
+private:
+    ios_base::openmode _Mode{ios_base::in | ios_base::out};
+    _STD span<_Elem> _Buf{};
```
[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/spanstream:186]: Surprisingly it is. All involved compilers were *really* unhappy with the `span(span)` and the `span span()` member method and broke without the qualified calls

File: tests/std/tests/P0448R4_spanstream/test.cpp (hunk 4 above)
Comment (miscco) [reply tests/std/tests/P0448R4_spanstream/test.cpp:694]: I wanted to say that I feel like I have sufficiently tested the `rdbuf` interface in the tests above

File: stl/inc/spanstream (hunk 6 above)
[the remark this answers is not in the document]
Comment (AdamBucior) [reply stl/inc/spanstream:186]: Should we add some comment explaining that? It might be confusing for other reviewers.

[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/spanstream:190]: Note, that not *all* are necessary, but given that *some* are I thought it best to add them unconditionally here

File: tests/std/tests/P0448R4_spanstream/test.cpp (hunk 4 above)
Comment (AdamBucior) [reply tests/std/tests/P0448R4_spanstream/test.cpp:695]: I think it should just be removed.

Comment (miscco) [reply tests/std/tests/P0448R4_spanstream/test.cpp:695]: Would you be happy with a simple comment `// rdbuf already tested above`

Comment (AdamBucior) [reply tests/std/tests/P0448R4_spanstream/test.cpp:695]: 👍

File: stl/inc/spanstream (hunk 5 above)
[the remark this answers is not in the document]
Comment (MattStephanson) [reply stl/inc/spanstream:32]: I recall adding them for my `<chrono>` work, so I thought the consensus was to continue using them generally. I didn't realize it was only in old headers, sorry.

[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/spanstream]: Removed the shouty banners

File: stl/inc/spanstream (hunk 6 above)
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/inc/spanstream:189]: This occurs elsewhere in the library (e.g. `path` `string()` IIRC). We typically haven't commented this, but adding a comment here would be entirely reasonable (something about "avoid ambiguity with the span() member function" etc.).

[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/spanstream:189]: I would not want to trigger CI just for an additional comment. @StephanTLavavej if you go through it could you add it when you have some minor fixes?

File: tests/std/tests/P0448R4_iosfwd/test.cpp [hunk 7]
```diff
@@ -0,0 +1,123 @@
...
+
+    static void test_forward_declaration(wsyncbuf*);
+    static void test_forward_declaration(wosyncstream*);
+#endif // _HAS_CXX20
+
+#if defined(_CRTBLD)
+    static void test_forward_declaration(ushistream*);
+    static void test_forward_declaration(ushostream*);
+    static void test_forward_declaration(ushfilebuf*);
+#endif // defined(_CRTBLD)
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_iosfwd/test.cpp:73]: This can/should be deleted - `_CRTBLD` is defined only when building the STL's separately compiled sources, and is never defined for user/test code. (In fact, these aliases should not be present in the header at all; mentioned in #216 now.)

File: tests/std/tests/P0448R4_iosfwd/test.cpp [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+// Copyright (c) Microsoft Corporation.
+// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+
+#include <iosfwd>
+
+using namespace std;
+
+// Needs to be separately declared as a simple alias of streampos
+void test_forward_declaration(wstreampos*);
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_iosfwd/test.cpp:11]: What about `u8streampos`, `u16streampos`, and `u32streampos`?

File: tests/std/tests/P0448R4_iosfwd/test.cpp [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+int main() {
+    test_aliases aliases;
+    (void) aliases;
+
+    test_forward_declarations<char> forward_declarations_char;
+    (void) forward_declarations_char;
+
+    test_forward_declarations<wchar_t> forward_declarations_wchar_t;
+    (void) forward_declarations_wchar_t;
+}
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_iosfwd/test.cpp:123]: This isn't executing any code at runtime, so I believe that the test should be named `test.compile.pass.cpp`, we should have another function instantiating these classes, and then `main()` should be empty with the conventional compile-only comment:

https://github.com/microsoft/STL/blob/bd7adb4a932725f60ba096580c415616486ab64c/tests/std/tests/VSO_0180469_ptr_cat/test.compile.pass.cpp#L25

File: stl/inc/spanstream [hunk 10]
```diff
@@ -0,0 +1,396 @@
...
+
+        if (_Mode & ios_base::in) {
+            _Mysb::setg(_Buf.data(), _Buf.data(), _Buf.data() + _Buf.size());
+        }
+    }
+
+protected:
+    // [spanbuf.virtuals], overridden virtual functions
+    virtual pos_type __CLR_OR_THIS_CALL seekoff(
+        off_type _Off, ios_base::seekdir _Way, ios_base::openmode _Which = ios_base::in | ios_base::out) override {
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:111]: To avoid a stealth merge quasi-conflict with #2069, the 3 occurrences of `virtual ... override` in this header should be pre-emptively changed to just `override`.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]
Partial review (to be available as a video recording in the near future), I looked at everything except `stl/inc/spanstream` and `P0448R4_spanstream/test.cpp`.

**Comment by StephanTLavavej** [comment]
There are test failures; the first one I saw was:

```
C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(10): error C2182: 'test_forward_declaration': illegal use of type 'void'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(10): error C2365: 'test_forward_declaration': redefinition; previous definition was 'function'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(10): error C2065: 'u8streampos': undeclared identifier

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(10): error C2059: syntax error: ')'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(11): error C2182: 'test_forward_declaration': illegal use of type 'void'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(11): error C2365: 'test_forward_declaration': redefinition; previous definition was 'function'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(11): error C2065: 'u16streampos': undeclared identifier

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(11): error C2059: syntax error: ')'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(12): error C2182: 'test_forward_declaration': illegal use of type 'void'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(12): error C2365: 'test_forward_declaration': redefinition; previous definition was 'function'

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(12): error C2065: 'u32streampos': undeclared identifier

C:\a\1\s\tests\std\tests\P0448R4_iosfwd\test.compile.pass.cpp(12): error C2059: syntax error: ')'
```

File: stl/CMakeLists.txt [hunk 11]
```diff
@@ -182,6 +182,7 @@ set(HEADERS
     ${CMAKE_CURRENT_LIST_DIR}/inc/shared_mutex
     ${CMAKE_CURRENT_LIST_DIR}/inc/source_location
     ${CMAKE_CURRENT_LIST_DIR}/inc/span
+    ${CMAKE_CURRENT_LIST_DIR}/inc/spanstream
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/CMakeLists.txt:185]: @CaseyCarter's internal VS-PR-339694 has taught the IDE to recognize this as a C++ header. We'll still need to follow the other checklist steps.

File: stl/inc/spanstream [hunk 12]
```diff
@@ -0,0 +1,396 @@
...
+        }
+
+        if (_Mode & ios_base::in) {
+            _Mysb::setg(_Buf.data(), _Buf.data(), _Buf.data() + _Buf.size());
+        }
+    }
+
+protected:
+    // [spanbuf.virtuals], overridden virtual functions
+    pos_type __CLR_OR_THIS_CALL seekoff(
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:110]: The occurrences of `__CLR_OR_THIS_CALL` in this file can be dropped - `/clr` is incompatible with C++20 (and C++23) so we can assume we're always compiling native code where this expands to nothing. `<syncstream>` overrode `overflow()` without this explicit calling convention (unlike `<fstream>` and `<strstream>` where it is definitely necessary), so omitting it here would be consistent with that new practice.

(The explicit calling convention is necessary for older code, to ensure that the virtual member function exactly matches the base class.)

Occurs below.

File: stl/inc/spanstream [hunk 13]
```diff
@@ -0,0 +1,396 @@
...
+        off_type _Off, ios_base::seekdir _Way, ios_base::openmode _Which = ios_base::in | ios_base::out) override {
+        const bool _Sequence_in  = _Which & ios_base::in;
+        const bool _Sequence_out = _Which & ios_base::out;
+        switch (_Way) {
+        case ios_base::beg:
+            {
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:116]: These braces for `case ios_base::beg` are unnecessary as no variable is being introduced here.

File: stl/inc/spanstream [hunk 14]
```diff
@@ -0,0 +1,396 @@
...
+                if (static_cast<size_t>(_Off) > _Buf.size()) { // negative wraparound to positive to save a compare
+                    return pos_type(off_type(-1)); // [spanbuf.virtuals]/5 report failure
+                }
+
+                break;
+            }
+        case ios_base::end:
+            {
+                // [spanbuf.virtuals]/4.3 baseoff =
+                const auto _Baseoff = _Mode & ios_base::out && !(_Mode & ios_base::in)
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:127]: This is mixing bitwise and logical operators, so we conventionally use parentheses to disambiguate the (notoriously confusing for humans) precedence: `(_Mode & ios_base::out)`

File: stl/inc/spanstream [hunk 15]
```diff
@@ -0,0 +1,396 @@
...
+                                        ? static_cast<off_type>(_Mysb::pptr() - _Mysb::pbase())
+                                        : static_cast<off_type>(_Buf.size());
+
+                _Off += _Baseoff;
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:131]: `_Off` and `_Baseoff` are signed `long long`, so this is performing signed addition without an overflow check ("if `baseoff + off` would overflow" is the first thing we need to check).

In contrast, the logic for `ios_base::cur` is very strict about checking for overflow and out-of-bounds before performing the addition.

File: stl/inc/spanstream [hunk 16]
```diff
@@ -0,0 +1,396 @@
...
+                if (static_cast<size_t>(_Off) > _Buf.size()) { // negative wraparound to positive to save a compare
+                    return pos_type(off_type(-1)); // [spanbuf.virtuals]/5 report failure
+                }
+
+                break;
+            }
+        case ios_base::cur:
+            {
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:139]: Unnecessary parens for the `case ios_base::cur` too.

File: stl/inc/spanstream [hunk 17]
```diff
@@ -0,0 +1,396 @@
...
+protected:
+    // [spanbuf.virtuals], overridden virtual functions
+    pos_type __CLR_OR_THIS_CALL seekoff(
+        off_type _Off, ios_base::seekdir _Way, ios_base::openmode _Which = ios_base::in | ios_base::out) override {
+        const bool _Sequence_in  = _Which & ios_base::in;
+        const bool _Sequence_out = _Which & ios_base::out;
+        switch (_Way) {
+        case ios_base::beg:
+            {
+                // [spanbuf.virtuals]/4.1 baseoff = 0
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:117]: All of the citations to specific paragraphs need to be qualified with N4892, in case the paragraphs are renumbered in the future. Occurs repeatedly below (I just searched for `]/`). Mentions of stable names alone are fine when unqualified.

File: stl/inc/spanstream [hunk 18]
```diff
@@ -0,0 +1,396 @@
...
+                    return pos_type(off_type(-1)); // report failure
+                }
+                break;
+            }
+        default:
+            return pos_type(off_type(-1)); // report failure
+        }
+
+        // [spanbuf.virtuals]/4: For a sequence to be positioned, if its next pointer is a null pointer and newoff
+        // is not equal 0, the positioning operation fails.
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:161]: Should say "not equal to" (I know this isn't a literal quote but the grammar should be correct).

File: stl/inc/spanstream [hunk 19]
```diff
@@ -0,0 +1,396 @@
...
+        if (_Off != 0 && ((_Sequence_in && !_Mysb::gptr()) || (_Sequence_out && !_Mysb::pptr()))) {
+            return pos_type(off_type(-1));
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:163]: All of the other failure returns have the comment `// report failure`.

**Review by StephanTLavavej — COMMENTED** [review]
Video reviewed `basic_spanbuf` and the recent commits; `basic_ispanstream` and below, and the new test, remain. (This is a lot of code, thanks for working on it! :heart_eyes_cat:)

File: tests/std/tests/P1502R1_standard_library_header_units/test.cpp [hunk 20]
```diff
@@ -698,6 +698,29 @@ int main() {
         static_assert(mid[0] == 22 && mid[1] == 33 && mid[2] == 44);
     }
 
+    {
+        puts("Testing <spanstream>.");
+        char ibuffer[] = "1 2 3 4 5";
+        ispanstream is{span<char>{ibuffer}};
```
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1502R1_standard_library_header_units/test.cpp:704]: Unfortunately that does not work-.

`ispanstream` is specified as `basic_ispanstream<char>` and there is only a constructor that takes a `span<charT>` and not a `span<const charT>` Also when trying to use a `basic_ispanstream<const char>` it blows up in the spanbuf with 

```
C:\STL\out\build\x64\out\inc\streambuf(324): error C3892: '_Ptr': you cannot assign to a variable that is const
```

File: stl/inc/spanstream [hunk 21]
```diff
@@ -0,0 +1,396 @@
...
+            _Mysb::setg(_Buf.data(), _Buf.data(), _Buf.data() + _Buf.size());
+        }
+    }
+
+    basic_spanbuf(const basic_spanbuf&) = delete;
+    basic_spanbuf(basic_spanbuf&& _Right)
+        : _Mysb(_STD move(_Right)), _Mode(_STD move(_Right._Mode)), _Buf(_STD move(_Right._Buf)) {
+        _Right.setp(nullptr, nullptr, nullptr);
+        _Right.setg(nullptr, nullptr, nullptr);
+    }
```
[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/spanstream:67]: Went with `_Buf(_STD exchange(_Right._Buf, {}))`

File: tests/std/tests/P1502R1_standard_library_header_units/test.cpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1502R1_standard_library_header_units/test.cpp:704]: Added the test albeit they break the modules build

[the remark this answers is not in the document]
Comment (CaseyCarter) [reply tests/std/tests/P1502R1_standard_library_header_units/test.cpp:704]: > `ispanstream` is specified as `basic_ispanstream<char>` and there is only a constructor that takes a `span<charT>` and not a `span<const charT>`

[ispanstream.ctor]/3 says that `template<class ROS> explicit basic_ispanstream(ROS&& s)` accepts arguments that convert to `span<const charT>`. Certainly a `span<const charT>` is such an argument?

[the remark this answers is not in the document]
Comment (miscco) [reply tests/std/tests/P1502R1_standard_library_header_units/test.cpp:704]: Yeah that was me being confused by the fact that the modules build broke being unable to find the constructor

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` (resolving trivial adjacent-add conflicts in `<yvals_core.h>`). I've also reduced and reported DevCom-1511903 "Standard Library Header Units: Bogus error C2440 when `convertible_to` constrains a constructor", and skipped the affected part of the test. (I've also removed the `__cpp_lib_concepts` checks there - this test isn't running for EDG yet, and it can therefore assume that concepts are available.)

File: stl/inc/spanstream [hunk 22]
```diff
@@ -0,0 +1,386 @@
...
+        _Mybase::swap(_Right);
+        _STD swap(_Buf, _Right._Buf);
+    }
+
+    // N4892 [ispanstream.members], member functions
+    _Mysb* rdbuf() const noexcept {
+        return const_cast<_Mysb*>(_STD addressof(_Buf));
+    }
+
+    span<const _Elem> span() const noexcept {
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:237]: The `rdbuf()` and `span()` observers should be `_NODISCARD`.

Occurs below.

Comment (StephanTLavavej) [inline stl/inc/spanstream:237]: Should say `_STD` before `span<const _Elem>` for consistency.

Occurs below.

File: stl/inc/spanstream [hunk 23]
```diff
@@ -0,0 +1,386 @@
...
+        return this->rdbuf()->span();
+    }
+
+    void span(_STD span<_Elem> _Span) noexcept {
+        this->rdbuf()->span(_Span);
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:242]: `rdbuf()` is a direct member function, so we don't need to say `this->`.

Occurs below.

File: stl/inc/spanstream [hunk 24]
```diff
@@ -0,0 +1,386 @@
...
+    // clang-format on
+#endif // __cpp_lib_concepts
+
+    // N4892 [ispanstream.assign], assignment and swap
+    basic_ispanstream& operator=(const basic_ispanstream&) = delete;
+
+    basic_ispanstream& operator=(basic_ispanstream&& _Right) {
+        _Mybase::swap(_Right);
+        _STD swap(_Buf, _Right._Buf);
+    }
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:225]: Missing `return *this;`.

Occurs below.

File: stl/inc/spanstream [hunk 25]
```diff
@@ -0,0 +1,386 @@
...
+
+    void swap(basic_spanstream& _Right) {
+        _Mybase::swap(_Right);
+        _STD swap(_Buf, _Right._Buf);
+    }
+
+    // N4892 [spanstream.members], members
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:356]: Hyper-nitpick, the previous comments (and the Standard section name) said "member functions".

File: stl/inc/spanstream [hunk 26]
```diff
@@ -0,0 +1,386 @@
...
+        _Mybase::swap(_Right);
+        _STD swap(_Buf, _Right._Buf);
+    }
+
+    // N4892 [ospanstream.members], member functions
+    _Mysb* rdbuf() const noexcept {
+        return const_cast<_Mysb*>(_STD addressof(_Buf));
+    }
+
+    span<const _Elem> span() const noexcept {
```
Comment (StephanTLavavej) [inline stl/inc/spanstream:305]: Unlike `basic_ispanstream` above, `basic_ospanstream` needs to return `span<_Elem>` here.

Occurs below for `basic_spanstream`.

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 27]
```diff
@@ -0,0 +1,1027 @@
...
+        const test_buf default_constructed{};
+        assert(default_constructed.span().data() == nullptr);
+        assert(default_constructed.eback() == nullptr);
+        assert(default_constructed.gptr() == nullptr);
+        assert(default_constructed.egptr() == nullptr);
+        assert(default_constructed.pbase() == nullptr);
+        assert(default_constructed.pptr() == nullptr);
+        assert(default_constructed.epptr() == nullptr);
+
+        const test_buf mode_constructed{ios_base::in};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:64]: Should technically include `<ios>`.

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 28]
```diff
@@ -0,0 +1,1027 @@
...
+    using Spanbuf::setp;
+
+    using Spanbuf::seekoff;
+    using Spanbuf::seekpos;
+    using Spanbuf::setbuf;
+};
+
+template <class CharT>
+void test_spanbuf() {
+    using test_buf = test_buf<basic_spanbuf<CharT>>;
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:52]: I find it confusing to have a typedef that shadows a template. It looks like the least invasive way to avoid this would be to rename the template to `basic_test_buf`.

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 29]
```diff
@@ -0,0 +1,1027 @@
...
+        const test_buf span_mode_unknown_constructed{span<CharT>{buffer}, 0};
+        assert(span_mode_unknown_constructed.span().data() == buffer);
+        assert(span_mode_unknown_constructed.eback() == nullptr);
+        assert(span_mode_unknown_constructed.gptr() == nullptr);
+        assert(span_mode_unknown_constructed.egptr() == nullptr);
+        assert(span_mode_unknown_constructed.pbase() == nullptr);
+        assert(span_mode_unknown_constructed.pptr() == nullptr);
+        assert(span_mode_unknown_constructed.epptr() == nullptr);
+
+        test_buf move_constructed{move(span_constructed)};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:127]: Technically need `<utility>`.

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 30]
```diff
@@ -0,0 +1,1027 @@
...
+        // passes and moves to buffer size - off
+        result = input_buffer.seekoff(-5, ios_base::end, ios_base::in);
+        assert(result == 5);
+
+        // always from front
+        result = input_buffer.seekoff(-7, ios_base::end, ios_base::in);
+        assert(result == 3);
+
+        // integer overflow due to large off
+        result = input_buffer.seekoff(numeric_limits<long long>::max(), ios_base::end, ios_base::in);
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:298]: Need `<limits>`.

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 31]
```diff
@@ -0,0 +1,1027 @@
...
+
+        // off larger than buffer size -> fail
+        result = inout_buffer.seekoff(20, ios_base::cur, ios_base::out);
+        assert(result == -1);
+
+        // off negative -> fail
+        result = inout_buffer.seekoff(-1, ios_base::cur, ios_base::out);
+        assert(result == -1);
+
+        // Moves input sequece to position 3
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:474]: Typo.

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 32]
```diff
@@ -0,0 +1,1027 @@
...
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->gptr() == buffer);
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->egptr() == end(buffer));
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->pbase() == buffer);
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->pptr() == buffer);
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->epptr() == end(buffer));
+    }
+
+    { // span
+        CharT buffer[10];
+        basic_ospanstream<CharT> is{span<CharT>{buffer}};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:760]: Nitpick: A `basic_ospanstream` probably shouldn't be named `is`. Occurs below.

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 33]
```diff
@@ -0,0 +1,1027 @@
...
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->gptr() == buffer);
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->egptr() == end(buffer));
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->pbase() == nullptr);
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->pptr() == nullptr);
+        assert(static_cast<test_buf*>(span_mode_constructed.rdbuf())->epptr() == nullptr);
+    }
+
+    { // span
+        CharT buffer[10];
+        basic_ospanstream<CharT> is{span<CharT>{buffer}};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:892]: This is `test_spanstream()`, but a `basic_ospanstream` is here (also named `is`). Below there's a `basic_ispanstream<CharT> is`. Will need to check for any other occurrences.

**Review by StephanTLavavej — COMMENTED** [review]
Thanks! I'll validate and push changes.

File: stl/inc/spanstream (hunk 6 above)
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/inc/spanstream:179]: I've finally remembered to add this comment and will push it in my next commits.

File: stl/inc/spanstream [hunk 34]
```diff
@@ -0,0 +1,386 @@
...
+            }
+
+            break;
+        case ios_base::end:
+            {
+                // N4892 [spanbuf.virtuals]/4.3 baseoff =
+                const auto _Baseoff = (_Mode & ios_base::out) && !(_Mode & ios_base::in)
+                                        ? static_cast<off_type>(_Mysb::pptr() - _Mysb::pbase())
+                                        : static_cast<off_type>(_Buf.size());
+                if (_Off > (numeric_limits<off_type>::max) () - _Baseoff) { // overflow, _Baseoff is always positive
```
[the remark this answers is not in the document]
Comment (StephanTLavavej) [reply stl/inc/spanstream:120]: Temporarily adding an `_STL_INTERNAL_CHECK` confirmed my suspicion that this comment should say "non-negative".

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Note that I had to push an additional commit, beyond my code review feedback, to fix how `basic_spanstream` is constructed in the test (it must be constructed from a `span` of modifiable characters). See https://github.com/microsoft/STL/pull/2029/commits/205178e564202bcbd30493404ef271bd277248cd .

**Comment by miscco** [comment]
We should add a test that the returned span is indeed mutable for both the const and non-const versions

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 35]
```diff
@@ -646,6 +646,10 @@ void test_ispanstream() {
         assert(is.span().data() == buffer);
         assert(is.span().size() == size(buffer));
```
Comment (StephanTLavavej) [inline tests/std/tests/P0448R4_spanstream/test.cpp:648]: The `vcpkg` submodule has been unintentionally re-added.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

**Review by StephanTLavavej — APPROVED** [review]

File: tests/std/tests/P0448R4_spanstream/test.cpp [hunk 36]
```diff
@@ -0,0 +1,1053 @@
...
+        CharT buffer2[10];
+        input_buffer.span(span<CharT>{buffer2});
+        assert(input_buffer.span().data() == buffer2);
+        assert(input_buffer.span().size() == size(buffer2));
+
+        output_buffer.span(span<CharT>{buffer2});
+        assert(output_buffer.span().data() == buffer2);
+        assert(output_buffer.span().size() == 0);
+
+        test_buf hungry_buffer{span<CharT>{buffer1}, ios_base::out | ios_base::ate};
```
Comment (barcharcraz) [inline tests/std/tests/P0448R4_spanstream/test.cpp:215]: amazing name choice. This made my day

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
@miscco I pushed changes to use variable templates in the test as @barcharcraz suggested. It's slightly fewer lines of source code, and avoids emitting function calls (which isn't a big deal in test code, but can make stepping through a bit nicer). I also took this opportunity to rename `get_input_array` to `input_ptr` because `"1 2 3 4 5"` (in both the old and new code) decays from an array to a pointer.

**Review by barcharcraz — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo now. Please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for continuing to implement a stream of `span` features! :joy_cat: :rocket: :tada:
