### PR TITLE
Update `variant` "all types same/convertible" metaprogramming

### LINKED ISSUE #2770: `<variant>`: `visit()` combinatoric catastrophe
Reported by @xiangfan-ms:

```
C:\Temp>type meow.cpp
```
```cpp
#include <cassert>
#include <variant>
using namespace std;

struct S {
    int operator()(auto, auto, auto, auto, auto) const {
        return 1729;
    }
};

int main() {
    using V = variant<char, int, long, long long>;
    assert(visit<int>(S{}, V{'a'}, V{'b'}, V{10}, V{20L}, V{30LL}) == 1729);
}
```

MSVC accepts this due to the compiler's type trait optimizations, but it still takes a significant amount of time to compile:

```
C:\Temp>cl /EHsc /nologo /W4 /MTd /Od /std:c++20 /Bt meow.cpp
meow.cpp
time(C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\bin\HostX64\x64\c1xx.dll)=5.114s
time(C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\bin\HostX64\x64\c2.dll)=0.135s
  OptRef: Total time = 0.000s
  OptIcf: Total time = 0.015s
Pass 1: Interval #1, time = 0.062s
Pass 2: Interval #2, time = 0.016s
Final: Total time = 0.078s
time(C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\bin\HostX64\x64\link.exe)=0.082s

C:\Temp>meow
```

Clang rejects this, because `<variant>` massively exceeds the compiler's template limits:

```
C:\Temp>clang-cl /EHsc /nologo /W4 /MTd /Od /std:c++20 meow.cpp
In file included from meow.cpp:2:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\variant:15:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\exception:12:
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\type_traits(52,27): fatal error:
      recursive template instantiation exceeded maximum depth of 1024
    using type = typename _Conjunction<_Next::value, _Next, _Rest...>::type;
                          ^
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\type_traits(52,27): note: in
      instantiation of template class 'std::_Conjunction<true, std::is_convertible<int, int>, std::is_convertible<int,
      int>, std::is_convertible<int, int>, std::is_convertible<int, int>, std::is_convertible<int, int>,
      std::is_convertible<int, int>, std::is_convertible<int, int>, std::is_convertible<int, int>,
[...]
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\include\variant(1671,23): note: in
      instantiation of template class 'std::_Variant_all_visit_results_implicitly_convertible<int, S,
      std::_Meta_list<std::integer_sequence<unsigned long long, 0, 0, 0, 0, 0>, std::integer_sequence<unsigned long
      long, 0, 0, 0, 0, 1>, std::integer_sequence<unsigned long long, 0, 0, 0, 0, 2>, std::integer_sequence<unsigned
      long long, 0, 0, 0, 0, 3>, std::integer_sequence<unsigned long long, 0, 0, 0, 0, 4>,
[...]
      long long, 4, 4, 4, 4, 3>, std::integer_sequence<unsigned long long, 4, 4, 4, 4, 4>>, std::variant<char, int,
      long, long long> &&, std::variant<char, int, long, long long> &&, std::variant<char, int, long, long long> &&,
      std::variant<char, int, long, long long> &&, std::variant<char, int, long, long long> &&>' requested here
        static_assert(_Variant_all_visit_results_implicitly_convertible<_Ret, _Callable, _ListOfIndexVectors,
                      ^
meow.cpp(13,12): note: in instantiation of function template specialization 'std::visit<int, S, std::variant<char, int,
      long, long long>, std::variant<char, int, long, long long>, std::variant<char, int, long, long long>,
      std::variant<char, int, long, long long>, std::variant<char, int, long, long long>, void>' requested here
    assert(visit<int>(S{}, V{'a'}, V{'b'}, V{10}, V{20L}, V{30LL}) == 1729);
           ^
1 error generated.
```

This is the code that's responsible:

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/variant#L1662-L1675

https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/variant#L1502-L1532

As @CaseyCarter explained, `variant<char, int, long, long long>` has 5 possible states (including `valueless_by_exception`), so `visit`ing 5 `variant`s will examine 5^5 = 3,125 combinations of argument types.

I (@StephanTLavavej :cat:) wonder whether we could use tree-like expansion instead of linear pack expansion to avoid the length limits here. (We'd still be doing the same amount of work, just not with huge type lists.) However, I am uncertain whether the actual visitation would also need to be changed: https://github.com/microsoft/STL/blob/17fde2cbab6e8724d81c9555237c9a623d7fb954/stl/inc/variant#L1677-L1678

### PR DESCRIPTION
**Pull request by CaseyCarter**
And a few other minor changes while we're here. I've separated changes out by commit for ease of review, but this should be squash merged. The most significant change here - others are self-explanatory - replaces the metaprogramming used to enforce the Standard's requirements that "For each valid pack m, e(m) is a valid expression. All such expressions are of the same type
and value category" ([variant.visit]/5). 

here are different mechanisms to validate the requirement for `visit<R>` and for plain `visit`. Previously, we created a single typelist where each type represented one possible configuration of the set of argument variants to a visit call, and then folded over a single giant pack expansion of visitor evaluations ensuring they had the same type and value category (or are all convertible to `R` for `visit<R>`). This was enormously expensive for throughput when the number of possible states is large since the compilers burn a lot of memory maintaining long typelists. The new version uses tree evaluation, where each internal node of the tree `and`s together the result of evaluating its child nodes, which each correspond to a possible state of a single argument variant. Leaves correspond to potential calls and have a boolean value indicating whether that potential call has the same type and value category as the first valid configuration (has a type and value category convertible to the result type for `visit<R>`).

The resulting speedup for the long-pole `/analyze` configs of the `visit` tests in the "Update LLVM" PR is around 50%.

Fixes #2770. 
Unblocks #2976.

### CODE REVIEW

File: stl/inc/variant [hunk 1]
```diff
@@ -30,16 +30,7 @@ _STL_DISABLE_CLANG_WARNINGS
...
-struct _All_same<_First, _Rest...> : bool_constant<conjunction_v<is_same<_First, _Rest>...>> {}; // variadic is_same
-
-template <class _To, class... _From>
-using _Convertible_from_all =
-    bool_constant<conjunction_v<_Invoke_convertible<_From, _To>...>>; // variadic _Invoke_convertible
-
-template <class...>
-struct _Meta_list {}; // a sequence of types
+struct _Meta_list; // a sequence of types (not defined)
 struct _Meta_nil {};
```
Comment (StephanTLavavej) [inline stl/inc/variant:34]: Pre-existing: `_Meta_nil` is unused.

File: stl/inc/variant [hunk 2]
```diff
@@ -1481,40 +1471,18 @@ template <class _Callable, class _IndexSequence, class... _Variants>
 struct _Variant_single_visit_result; // undefined
 
 template <class _Callable, size_t... _Idxs, class... _Variants>
-struct _Variant_single_visit_result<_Callable, index_sequence<_Idxs...>,
-    _Variants...> { // result type/category from invoking _Callable with the elements of
-                    // _Variants... at (_Idxs - 1)...
+struct _Variant_single_visit_result<_Callable, index_sequence<_Idxs...>, _Variants...> {
```
Comment (StephanTLavavej) [inline stl/inc/variant:1474]: `_Variant_single_visit_result` is now unused.

File: stl/inc/variant [hunk 3]
```diff
@@ -1616,10 +1584,37 @@ constexpr _Ret _Visit_impl(_Callable&& _Obj, _Variants&&... _Args) {
...
+        _STD _Variant_visit_index1(0, static_cast<_As_variant<_Variants>&>(_Args)...), static_cast<_Callable&&>(_Obj),
         static_cast<_As_variant<_Variants>&&>(_Args)...);
 }
 
+template <class _Expected, class _Callable, class _ArgList, class... _Variants>
+inline constexpr bool _Variant_all_visit_results_same = false;
+
+template <class _Expected, class _Callable, class... _Args>
+inline constexpr bool _Variant_all_visit_results_same<_Expected, _Callable, _Meta_list<_Args...>> =
+    is_same_v<decltype(_STD declval<_Callable>()(_STD declval<_Args>()...)), _Expected>;
```
Comment (StephanTLavavej) [inline stl/inc/variant:1596]: This appears to be a regression: `_STD declval<_Callable>()(_STD declval<_Args>()...)` is using the function call operator instead of the `invoke` protocol (as the old machinery did).

Also occurs in `_Variant_all_visit_results_convertible`.

This also indicates a lack of test coverage for PMFs/PMDs.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]

File: stl/inc/variant (hunk 3 above)
Comment (StephanTLavavej) [reply stl/inc/variant:1596]: Regression confirmed:

```
D:\GitHub\STL\out\build\x64>type meow.cpp
```
```cpp
#include <iostream>
#include <variant>
using namespace std;

struct Point2D {
    int x;
    int y;
};

struct Point3D : Point2D {
    int z;
};

int main() {
    using Var = variant<Point2D, Point3D>;

    Var v1{Point2D{10, 20}};
    Var v2{Point3D{30, 40, 50}};

    cout << visit(&Point2D::y, v1) << endl;
    cout << visit(&Point2D::y, v2) << endl;
}
```

Works with 17.4 Preview 1:

```
D:\GitHub\STL\out\build\x64>cl /EHsc /nologo /W4 /std:c++latest meow.cpp && meow
meow.cpp
20
40
```

Error with this PR:

```
D:\GitHub\STL\out\build\x64>cl /EHsc /nologo /W4 /std:c++latest meow.cpp && meow
meow.cpp
D:\GitHub\STL\out\build\x64\out\inc\variant(1596): error C2064: term does not evaluate to a function taking 1 arguments
D:\GitHub\STL\out\build\x64\out\inc\variant(1601): note: see reference to variable template 'const bool _Variant_all_visit_results_same<int &,int Point2D::*,std::_Meta_list<Point2D &> >' being compiled
D:\GitHub\STL\out\build\x64\out\inc\variant(1627): note: see reference to variable template 'const bool _Variant_all_visit_results_same<int &,int Point2D::*,std::_Meta_list<>,std::variant<Point2D,Point3D> &>' being compiled
meow.cpp(20): note: see reference to function template instantiation 'int &std::visit<intPoint2D::* ,Var&,void>(_Callable &&,Var &)' being compiled
        with
        [
            _Callable=int Point2D::*
        ]
D:\GitHub\STL\out\build\x64\out\inc\variant(1595): error C2064: term does not evaluate to a function taking 1 arguments
D:\GitHub\STL\out\build\x64\out\inc\variant(1595): error C2062: type 'unknown-type' unexpected
D:\GitHub\STL\out\build\x64\out\inc\variant(1596): error C3376: 'std::_Variant_all_visit_results_same<_Expected,_Callable,std::_Meta_list<_Args...>,>': only static data member templates are allowed
D:\GitHub\STL\out\build\x64\out\inc\variant(1601): error C2131: expression did not evaluate to a constant
D:\GitHub\STL\out\build\x64\out\inc\variant(1601): note: failure was caused by a read of an uninitialized symbol
D:\GitHub\STL\out\build\x64\out\inc\variant(1601): note: see usage of 'std::?$_Variant_all_visit_results_same@$RBAAB@$RBAAC@U?$_Meta_list@$$W$TBAAD@@std@@$$V<_Ret,intPoint2D::* ,std::_Meta_list<Point2D &>,>'
D:\GitHub\STL\out\build\x64\out\inc\variant(1627): error C2131: expression did not evaluate to a constant
D:\GitHub\STL\out\build\x64\out\inc\variant(1601): note: failure was caused by a read of an uninitialized symbol
D:\GitHub\STL\out\build\x64\out\inc\variant(1601): note: see usage of 'std::?$_Variant_all_visit_results_same@$RBAAB@$RBAAC@U?$_Meta_list@$$W$TBAAD@@std@@$$V<_Ret,intPoint2D::* ,std::_Meta_list<Point2D &>,>'
```

Comment (CaseyCarter) [reply stl/inc/variant:1596]: Just a bit of a GIANT HOLE in our test coverage.

File: tests/std/tests/P0088R3_variant/test.cpp [hunk 4]
```diff
@@ -7048,6 +7048,30 @@ namespace msvc {
...
+            int f() const {
+                return x;
+            }
+        };
+        struct derived : base {
+            int y;
+        };
+
+        void run_test() {
+            {
```
Comment (CaseyCarter) [inline tests/std/tests/P0088R3_variant/test.cpp:7064]: ...

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for making `variant` faster to compile! :rocket: :leopard: :rabbit2:
