### PR TITLE
<xutility> lexicographical_compare_three_way

### PR DESCRIPTION
**Pull request by AdamBucior**
# Description

Another part of #64. Decided to implement it in `<xutility>` because many containers will require it for `<=>` operator (ex. `array` which is getting rid of `<algorithm>` right now #482).

Depends on #513.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

File: stl/inc/xutility [hunk 1]
```diff
@@ -4667,6 +4667,56 @@ _NODISCARD bool lexicographical_compare(
...
+            const int _Ans   = _CSTD memcmp(_UFirst1, _UFirst2, _Num1 < _Num2 ? _Num1 : _Num2);
+            if (const auto _CmpResult = _Comp(_Ans, 0); _CmpResult != 0) {
+                return _CmpResult;
+            } else {
+                return _Num1 > _Num2 ? strong_ordering::greater
+                                     : _Num2 > _Num1 ? strong_ordering::less : strong_ordering::equal;
+            }
+        }
+    }
+    for (; _UFirst1 != _ULast1 && _UFirst2 != _ULast2; ++_UFirst1, (void) ++_UFirst2) {
```
Comment (miscco) [inline stl/inc/xutility]: Why is there a void cast?

Comment (AdamBucior) [reply stl/inc/xutility]: Probably because of comma operator. It's in every other algorithm.

Comment (StephanTLavavej) [reply stl/inc/xutility]: Yep, it defends against overloaded `operator,()`. (Nothing in the Standard forbids users from overloading that for their own types!)

**Comment by StephanTLavavej** [comment]
I assume that the build failure `error C2065: 'strong_ordering': undeclared identifier` is caused by the #513 dependency. We'll get that merged soon to unblock this PR.

File: stl/inc/xutility [hunk 2]
```diff
@@ -4667,6 +4667,56 @@ _NODISCARD bool lexicographical_compare(
...
+        if (const auto _CmpResult = _Comp(*_UFirst1, *_UFirst2); _CmpResult != 0) {
+            return _CmpResult;
+        }
+    }
+
+    return _UFirst1 != _ULast1 ? strong_ordering::greater
+                               : _UFirst2 != _ULast2 ? strong_ordering::less : strong_ordering::equal;
```
Comment (CaseyCarter) [inline stl/inc/xutility]: We can avoid some extra iterator comparisons by inlining the return statement into the loop body:
```suggestion
    for (;;) {
        if (_UFirst1 == _ULast1) {
            return _UFirst2 == _ULast2 ? strong_ordering::equal : strong_ordering::less;
        }
        
        if (_UFirst2 == _ULast2) {
            return strong_ordering::greater;
        }
        
        if (const auto _CmpResult = _Comp(*_UFirst1, *_UFirst2); _CmpResult != 0) {
            return _CmpResult;
        }
        
        ++_UFirst1;
        ++_UFirst2;
    }
```
(No, I don't particularly care that this is observably different from the overspecified [alg.three.way]/2. I've filed an LWG issue to have that defective wording fixed.)

File: stl/inc/xutility [hunk 3]
```diff
@@ -4667,6 +4667,63 @@ _NODISCARD bool lexicographical_compare(
...
+        }
+        
+        ++_UFirst1;
+        ++_UFirst2;
+    }
+}
+
+template <class _InIt1, class _InIt2>
+constexpr auto lexicographical_compare_three_way(_InIt1 _First1, _InIt1 _Last1, _InIt2 _First2, _InIt2 _Last2) {
+    return _STD lexicographical_compare_three_way(_First1, _Last1, _First2, _Last2, compare_three_way());
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: In new code, we prefer to use empty braces to construct objects (instead of empty parentheses), because braces don't look like function calls. (See #468.)

File: stl/inc/xutility [hunk 4]
```diff
@@ -4667,6 +4667,63 @@ _NODISCARD bool lexicographical_compare(
 }
 #endif // _HAS_CXX17
 
+#if defined(__cpp_impl_three_way_comparison) && defined(__cpp_lib_concepts)
+// FUNCTION TEMPLATE lexicographical_compare_three_way
+template <class _InIt1, class _InIt2, class _Cmp>
+constexpr auto lexicographical_compare_three_way(_InIt1 _First1, _InIt1 _Last1, _InIt2 _First2, _InIt2 _Last2,
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: This should be marked `_NODISCARD` because it's a pure observer. (That is, it wouldn't make sense to call this function and then discard the result, because the function has no other effects.)

File: stl/inc/xutility [hunk 5]
```diff
@@ -4667,6 +4667,63 @@ _NODISCARD bool lexicographical_compare(
...
+            return _CmpResult;
+        }
+        
+        ++_UFirst1;
+        ++_UFirst2;
+    }
+}
+
+template <class _InIt1, class _InIt2>
+constexpr auto lexicographical_compare_three_way(_InIt1 _First1, _InIt1 _Last1, _InIt2 _First2, _InIt2 _Last2) {
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: This should also be `_NODISCARD`.

File: stl/inc/xutility [hunk 6]
```diff
@@ -4667,6 +4667,63 @@ _NODISCARD bool lexicographical_compare(
...
+    auto _UFirst1      = _Get_unwrapped(_First1);
+    const auto _ULast1 = _Get_unwrapped(_Last1);
+    auto _UFirst2      = _Get_unwrapped(_First2);
+    const auto _ULast2 = _Get_unwrapped(_Last2);
+    using _UIt1        = decltype(_UFirst1);
+    using _UIt2        = decltype(_UFirst2);
+
+    if constexpr (conjunction_v<is_same<_Cmp, compare_three_way>, is_pointer<_UIt1>, is_pointer<_UIt2>,
+                      disjunction<
+                          conjunction<is_same<remove_pointer_t<_UIt1>, byte>, is_same<remove_pointer_t<_UIt2>, byte>>,
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: We provide an escape hatch that allows users to remove `std::byte` due to an unfortunate conflict with the Windows SDK (see #204) so this should be guarded. We should test `__cpp_lib_byte` (I have filed #564 because the rest of the STL isn't testing the Standard feature-test macro for this purpose). Otherwise, this header will fail to compile if the user has removed `std::byte`.

Comment (StephanTLavavej) [inline stl/inc/xutility]: `is_same` is sensitive to cv-qualifiers; `is_same_v<int, const int>` is `false`. Therefore, I believe that comparing a range of `byte` with a range of `const byte`, or comparing two ranges of `const byte`, will fail to activate this test.

File: stl/inc/xutility [hunk 7]
```diff
@@ -4667,6 +4667,63 @@ _NODISCARD bool lexicographical_compare(
...
+                          conjunction<_Is_character<remove_pointer_t<_UIt1>>, is_unsigned<remove_pointer_t<_UIt1>>,
+                              _Is_character<remove_pointer_t<_UIt2>>, is_unsigned<remove_pointer_t<_UIt2>>>>>) {
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: `_Is_character` is also sensitive to cv-qualifiers; `_Is_character<const unsigned char>` is `false`:

https://github.com/microsoft/STL/blob/d4ee5c3fb4abfe8492f2108384d6f4e0fd0afeae/stl/inc/xutility#L4106-L4121

Note that this is an interface difference between this internal type trait and the primary type categories (e.g. `is_integral` is specified to ignore top-level cv-qualifiers).

Perhaps you should introduce helper typedefs for `remove_const_t<remove_pointer_t<_UIt1>>` and similarly for `_UIt2`. (If the iterators aren't pointers after unwrapping, these won't be element types, but you simply won't inspect them. Alternatively, I suppose you could use iterator traits machinery to get the value types.)

File: stl/inc/xutility [hunk 8]
```diff
@@ -4667,6 +4667,63 @@ _NODISCARD bool lexicographical_compare(
...
+#ifdef __cpp_lib_is_constant_evaluated
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            const auto _Num1 = static_cast<size_t>(_ULast1 - _UFirst1);
+            const auto _Num2 = static_cast<size_t>(_ULast2 - _UFirst2);
+            const int _Ans   = _CSTD memcmp(_UFirst1, _UFirst2, _Num1 < _Num2 ? _Num1 : _Num2);
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: Would `(_STD min)(_Num1, _Num2)` be clearer? (It is now defined in `<utility>` so it's available in `<xutility>`.

File: stl/inc/xutility [hunk 9]
```diff
@@ -4667,6 +4667,63 @@ _NODISCARD bool lexicographical_compare(
...
+            if (const auto _CmpResult = _Ans <=> 0; _CmpResult != 0) {
+                return _CmpResult;
+            } else {
+                return _Num1 <=> _Num2;
+            }
+        }
+    }
+    for (;;) {
```
Comment (StephanTLavavej) [inline stl/inc/xutility]: I think there should be a newline before this `for` loop.

File: stl/inc/xutility [hunk 10]
```diff
@@ -4667,6 +4667,56 @@ _NODISCARD bool lexicographical_compare(
...
+                          conjunction<_Is_character<remove_pointer_t<_UIt1>>, is_unsigned<remove_pointer_t<_UIt1>>,
+                              _Is_character<remove_pointer_t<_UIt2>>, is_unsigned<remove_pointer_t<_UIt2>>>>>) {
+#ifdef __cpp_lib_is_constant_evaluated
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            const auto _Num1 = static_cast<size_t>(_ULast1 - _UFirst1);
+            const auto _Num2 = static_cast<size_t>(_ULast2 - _UFirst2);
+            const int _Ans   = _CSTD memcmp(_UFirst1, _UFirst2, _Num1 < _Num2 ? _Num1 : _Num2);
+            if (const auto _CmpResult = _Comp(_Ans, 0); _CmpResult != 0) {
```
[the remark this answers is not in the document]
Comment (miscco) [reply stl/inc/xutility]: Is that really correct?

As far as I understand it the user can provide its own comparison object?

So defaulting back to the original one might be the wrong comparison.

File: stl/inc/xutility (hunk 3 above)
Comment (AdamBucior) [reply stl/inc/xutility]: Done

File: stl/inc/xutility (hunk 4 above)
Comment (AdamBucior) [reply stl/inc/xutility]: Done

File: stl/inc/xutility (hunk 5 above)
Comment (AdamBucior) [reply stl/inc/xutility]: Done

File: stl/inc/xutility (hunk 6 above)
Comment (AdamBucior) [reply stl/inc/xutility]: Done

Comment (AdamBucior) [reply stl/inc/xutility]: Fixed

File: stl/inc/xutility (hunk 7 above)
Comment (AdamBucior) [reply stl/inc/xutility]: Fixed

File: stl/inc/xutility (hunk 8 above)
Comment (AdamBucior) [reply stl/inc/xutility]: Done

File: stl/inc/xutility (hunk 9 above)
Comment (AdamBucior) [reply stl/inc/xutility]: Done

File: stl/inc/xutility (hunk 10 above)
[the remark this answers is not in the document]
Comment (CaseyCarter) [reply stl/inc/xutility]: > As far as I understand it the user can provide its own comparison object?

Had the user provided an object whose type isn't `std::compare_three_way` we wouldn't be in this `if constexpr` branch.

File: stl/inc/xutility [hunk 11]
```diff
@@ -4667,6 +4667,69 @@ _NODISCARD bool lexicographical_compare(
...
+                          conjunction<_Is_character<_Ty1>, is_unsigned<_Ty1>, _Is_character<_Ty2>,
+                              is_unsigned<_Ty2>>>>) {
+#ifdef __cpp_lib_is_constant_evaluated
+        if (!_STD is_constant_evaluated())
+#endif // __cpp_lib_is_constant_evaluated
+        {
+            const auto _Num1 = static_cast<size_t>(_ULast1 - _UFirst1);
+            const auto _Num2 = static_cast<size_t>(_ULast2 - _UFirst2);
+            const int _Ans   = _CSTD memcmp(_UFirst1, _UFirst2, (_STD min)(_Num1, _Num2));
+            if (const auto _CmpResult = _Ans <=> 0; _CmpResult != 0) {
```
Comment (BillyONeal) [inline stl/inc/xutility]:
```suggestion
            if (_Ans == 0) {
                return _Num1 <=> _Num2;
            } else {
                return _Ans <=> 0;
            }
```

Comment (BillyONeal) [reply stl/inc/xutility]: The suggestion is to replace the whole if/else with that, don't know how to make GitHub do that :/

Comment (CaseyCarter) [reply stl/inc/xutility]: Click and hold the "leave a comment" `+`:

image

Then drag down some number of lines and release:

image

Comment (AdamBucior) [reply stl/inc/xutility]: Done

**Comment by AdamBucior** [comment]
> This change is missing test coverage.



> Needs tests :)

OK, I will try to add some tests.

**Comment by AdamBucior** [comment]
Should I add these tests to `P0768R1_spaceship_operator` or make a new folder `P0768R1_lexicographical_compare_three_way`?

**Comment by StephanTLavavej** [comment]
> Should I add these tests to `P0768R1_spaceship_operator`

I think that's fine - the test is small, and this is closely related.

**Comment by AdamBucior** [comment]
I added some tests, I hope they're ok.

**Comment by StephanTLavavej** [comment]
We merged #513 to `master`, so I pushed a merge here and the build is succeeding! 😸

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 12]
```diff
@@ -119,6 +122,99 @@ static_assert(test_common_type<std::strong_ordering, std::partial_ordering>());
...
+    using std::begin, std::end;
+    auto ret = std::lexicographical_compare_three_way(begin(left), end(left), begin(right), end(right));
+    auto ret2 =
+        std::lexicographical_compare_three_way(begin(left), end(left), begin(right), end(right), my_cmp_three_way);
+    assert(ret == ret2);
+    return ret;
+}
+
+template <class Ty1, class Ty2 = Ty1>
+constexpr void test_algorithm_compiletime() {
```
Comment (BillyONeal) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp]: You can make this thing "constexpr bool", add "return true", change the static_asserts to assesrts, then you can use this block for both compile time and run time.

Comment (AdamBucior) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp]: Done

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 13]
```diff
@@ -119,6 +122,69 @@ static_assert(test_common_type<std::strong_ordering, std::partial_ordering>());
...
+    assert(compare(original, bigger) < 0);
+    assert(compare(bigger, original) > 0);
+
+    assert(compare(original, biggerAndLesser) > 0);
+    assert(compare(biggerAndLesser, original) < 0);
+
+    assert(compare(original, smallerAndGreater) < 0);
+    assert(compare(smallerAndGreater, original) > 0);
+
+    return true;
```
Comment (CaseyCarter) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp]: This is sufficient smoke testing for the general case, but we should also have some coverage with pointers-to-`memcmp`-able types for the "use `memcmp`" case.

Comment (AdamBucior) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp]: `mamcmp` case is already tested since iterators are unwrapped

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 14]
```diff
@@ -1,9 +1,12 @@
 // Copyright (c) Microsoft Corporation.
 // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 
+#include <algorithm>
+#include <array>
 #include <cassert>
 #include <compare>
 #include <type_traits>
+#include <vector>
```
[the remark this answers is not in the document]
Comment (AdamBucior) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp]: Done

[the remark this answers is not in the document]
Comment (AdamBucior) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp]: It used `vector` before for runtime tests but @BillyONeal suggested to use `array` for both runtime and compiletime. Removed this include.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp (hunk 13 above)
Comment (CaseyCarter) [reply tests/std/tests/P0768R1_spaceship_operator/test.cpp]: And the asymmetric-type tests ensure that we have non-`memcmp` coverage as well - nevermind.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 15]
```diff
@@ -119,6 +121,69 @@ static_assert(test_common_type<std::strong_ordering, std::partial_ordering>());
...
+    assert(ret == ret2);
+    return ret;
+}
+
+template <class Ty1, class Ty2 = Ty1>
+constexpr bool test_algorithm2() {
+    std::array<Ty1, 4> original{0, 1, 2, 3};
+    std::array<Ty2, 4> same{0, 1, 2, 3}, lesser{0, 1, 1, 3}, greater{0, 1, 3, 3};
+    std::array<Ty2, 3> smaller{0, 1, 2}, smallerAndGreater{0, 2, 3};
+    std::array<Ty2, 5> bigger{0, 1, 2, 3, 4}, biggerAndLesser{0, 1, 2, 2, 4};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp]: `std::array` is an aggregate (a `struct`) containing an aggregate (a built-in array). For clarity and to avoid compiler warnings (which Clang especially likes to emit), we conventionally avoid brace elision when initializing `std::array`. This means using two layers of braces: `std::array<Ty1, 4> original{{0, 1, 2, 3}};`

Comment (StephanTLavavej) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp]: We conventionally avoid declaring multiple variables on a single line (and have recently increased our consistency in product code). Our conventions for test code are somewhat more relaxed (e.g. I don't object to varying `const` placement), but I would still prefer to avoid multi-decls.

File: tests/std/tests/P0768R1_spaceship_operator/test.cpp [hunk 16]
```diff
@@ -119,6 +121,69 @@ static_assert(test_common_type<std::strong_ordering, std::partial_ordering>());
...
+    auto ret2 =
+        std::lexicographical_compare_three_way(begin(left), end(left), begin(right), end(right), my_cmp_three_way);
+    assert(ret == ret2);
+    return ret;
+}
+
+template <class Ty1, class Ty2 = Ty1>
+constexpr bool test_algorithm2() {
+    std::array<Ty1, 4> original{0, 1, 2, 3};
+    std::array<Ty2, 4> same{0, 1, 2, 3}, lesser{0, 1, 1, 3}, greater{0, 1, 3, 3};
```
Comment (StephanTLavavej) [inline tests/std/tests/P0768R1_spaceship_operator/test.cpp]: Although you aren't `using namespace std` here, I would still prefer to see a different identifier than `greater` which already has a different purpose within `std`.

**Comment by StephanTLavavej** [comment]
My comments are small so I'm just going to push changes and batch this up for Microsoft-internal testing. 😸

**Comment by StephanTLavavej** [comment]
I've submitted a Microsoft-internal PR for this; please don't push any more changes to this branch, and we should be able to merge it very soon. :-)

**Comment by StephanTLavavej** [comment]
Thanks for implementing this algorithm, @AdamBucior! Looking at #64's checklist, it appears that you may have completed WG21-P0768 except for a feature-test macro update; I'll check with @CaseyCarter. 😺
