### ISSUE TITLE
<chrono>: Regression in VS 17.7.0 Preview 1.0 with legacy std modules

### ISSUE THREAD

**Issue by matbech** [microsoft/STL#3706]
This is a regression with VS 17.7.0 Preview 1.0 and the legacy std modules:
```
// no compile error if chrono is not included prior to std.core
#include <chrono>

import std.core;

int main()
{
  std::chrono::duration<float>(std::chrono::high_resolution_clock::now().time_since_epoch());
  return 0;
}
```
Fails with:
```
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.37.32705\include\__msvc_chrono.hpp(268,56): error C2752: 'std::common_type<_Rep1,_Rep2>': more than one partial specialization matches the template argument list
1>        with
1>        [
1>            _Rep1=float,
1>            _Rep2=float
1>        ]
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.37.32705\include\type_traits(1242,8): message : could be 'std::common_type<_Ty1,_Ty2>'
1>D:\a\_work\1\s\binaries\x86ret\inc\type_traits(1242,8): message : or       'std::common_type<_Ty1,_Ty2>'
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.37.32705\include\__msvc_chrono.hpp(268,35): message : see reference to alias template instantiation 'std::common_type_t<_Rep1,_Rep2>' being compiled
1>        with
1>        [
1>            _Rep1=float,
1>            _Rep2=float
1>        ]
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.37.32705\include\type_traits(1233,28): message : see reference to class template instantiation 'std::common_type<_Ty1,_Ty1>' being compiled
1>        with
1>        [
1>            _Ty1=std::chrono::duration<float,std::ratio<1,1>>
1>        ]
```

This used to work with all 17.6.* versions. It looks more like a compiler bug which is triggered by the specialization of templates. In this case std::common_type in chrono.

**Comment by StephanTLavavej** [comment]
Thanks for reporting this issue. At this time, the MSVC compiler is not capable of handling classic `#include`s mixed with `import`s of named modules (either the old experimental `std.core` or the new Standard `std`), and compiler errors may or may not happen in this scenario, which was never supported. The compiler team is acutely aware of this implementation limitation and is working on lifting it in the future. (FYI @cdacamar)

Separately, we strongly recommend migrating any code using the old experimental modules to using the new Standard modules, which are also better for build throughput.
