### PR TITLE
Avoid evil macros

### PR DESCRIPTION
**Pull request by StephanTLavavej**
ICU previously macroized these reserved names. This was fixed by https://github.com/unicode-org/icu/pull/1555 on 2021-02-01, but old versions of ICU are still being used by various projects. Let's avoid these names for now. I haven't added test coverage because the UCRT uses some of these reserved names (which it's getting away with, due to the specific order in which headers are being included).

Fixes VSO-1837381 "\[RWC\]\[prod/fe\]\[Regression\] PDFium failed with error C2209: `'std::_Aligned_storage_t<64,8>'`: aliases cannot be used in constructor declarations".

* `_Cs` => `_Cs_storage`
  + This introduces a slight but acceptable asymmetry with `mutex.cpp`.
  + This is the actual fix for the regression introduced by #3763. We were getting away with the others.
* `_No` => `_Nope`
  + This makes `<deque>` `_Is_bidi` consistent with `<format>` `_Add_newline`, `<xlocale>` `_Case_sensitive`, etc.
* `_Mn` => `_Min_`, also `_Mx` => `_Max_` for consistency
  + This is our conventional pattern for avoiding parameters shadowing data members.
* `_Cc` => `_Cx`, also `_Yy` => `_Yx` and `_Nn` => `_Nx` for consistency
  + This is our common pattern for "single letter" variable names.
* `_Pi` => `_Pi_val`

### CODE REVIEW

**Review by fsb4000 — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.
