### ISSUE TITLE
<functional>: Failed to specialize function template 'unknown-type std::invoke

### ISSUE THREAD

**Issue by jonesmz** [microsoft/STL#3983]
This minimal reproduction works on Clang 16 and GCC 13.2 , but not MSVC 19.35

MSVC 19.35: https://godbolt.org/z/9P4K8soPn
Clang 16: https://godbolt.org/z/Pv9vee8zh
GCC 13.2: https://godbolt.org/z/n6KTzhshP

First encountered on my local machine with toolchain version 14.36.32532

```
#include <functional>
struct Base
{
    virtual void virt_func() const = 0;
};

struct Derived : public Base
{
    void virt_func() const;
};

struct Proxy
{
    operator Derived() const;
};

void func(Base const& ctrl);

void break_msvc(void)
{
    std::invoke(&func, Proxy{});
}
```

Removing `virt_func` from `Base`, or making `Base::virt_func` virtual but not pure virtual, results in no error.

```
example.cpp
<source>(22): error C2672: 'std::invoke': no matching overloaded function found
C:/data/msvc/14.35.32217.1/include\type_traits(1568): note: could be 'unknown-type std::invoke(_Callable &&,_Ty1 &&,_Types2 &&...) noexcept(<expr>)'
<source>(22): note: Failed to specialize function template 'unknown-type std::invoke(_Callable &&,_Ty1 &&,_Types2 &&...) noexcept(<expr>)'
<source>(22): note: With the following template arguments:
<source>(22): note: '_Callable=void (__cdecl *)(const Base &)'
<source>(22): note: '_Ty1=Proxy'
<source>(22): note: '_Types2={}'
C:/data/msvc/14.35.32217.1/include\type_traits(1562): note: or       'unknown-type std::invoke(_Callable &&) noexcept(<expr>)'
<source>(22): note: 'unknown-type std::invoke(_Callable &&) noexcept(<expr>)': expects 1 arguments - 2 provided
Compiler returned: 2
```

**Comment by cpplearner** [comment]
Seems like a compiler bug.

```
struct Base
{
    virtual void virt_func() const = 0;
};

struct Derived : public Base
{
    void virt_func() const;
};

struct Proxy
{
    operator Derived() const;
};

void func(Base const& ctrl);

void break_msvc(void)
{
    using T = decltype(func(Proxy{}));  // error C2259: 'Base': cannot instantiate abstract class
}
```

**Comment by CaseyCarter** [comment]
Given the library-free minimal repro above, and the fact that the original program compiles just fine with clang-cl, this is clearly a bug in the compiler and not the STL. Please file a compiler bug on Developer Community.

**Comment by jonesmz** [comment]
> Please file a compiler bug on Developer Community.

No. I'm not going to waste my time doing that.

You may report it yourself.

**Comment by CaseyCarter** [comment]
This is DevCom-10448366. Feel free to followup there.
